# Generated by Django 5.0.6 on 2024-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_no',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
