# Generated by Django 5.0.6 on 2024-07-08 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_user_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_city', models.CharField(blank=True, max_length=50, null=True)),
                ('user_phno', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_profile_pic', models.ImageField(blank=True, null=True, upload_to='user_profile_pic')),
                ('user_banner', models.ImageField(blank=True, null=True, upload_to='user_banner')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Profiles',
        ),
    ]
